CREATE TABLE users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  hash_password varchar(40) NOT NULL,
  role_id integer(40) NOT NULL,
);