
CREATE TABLE users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  hash_password varchar(40) NOT NULL,
  role_id integer(40) NOT NULL,
);

INSERT INTO users
(first_name, last_name)
VALUES
('Ines', 'Robert');

CREATE TABLE roles (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   role_name VARCHAR(40) NOT NULL
);

CREATE TABLE poops (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(40) NOT NULL,
  author VARCHAR(40) NOT NULL,
  latitude VARCHAR(40) NOT NULL,
  longitude VARCHAR(40) NOT NULL,


);