
CREATE TABLE users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  hash_password varchar(40) NOT NULL,
  role_id integer(40) NOT NULL,
);

INSERT INTO poops
(first_name, last_name)
VALUES
('Ines', 'Robert');

CREATE TABLE roles (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   role_name VARCHAR(40) NOT NULL
);

CREATE TABLE poops (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(40) NOT NULL,
  author VARCHAR(40) NOT NULL,
  latitude VARCHAR(40) NOT NULL,
  longitude VARCHAR(40) NOT NULL,
  img_url VARCHAR(40) NOT NULL,
  date VARCHAR(40) NOT NULL,
);

INSERT INTO poops
(title, author, latitude, longitude, img_url, date)
VALUES
('Poop at Bahnhof', 'Robert Kalina', '48.19694', '16.33773', '/images/1.jpg', '23.12.2014'),
('Big one', 'Lisa Rath', '48.21174', '16.37706', '/images/1.jpg', '23.12.2014'),
('Stay away from here', 'Mex Miser', '48.20071', '16.37016', '/images/1.jpg', '23.12.2014'),
('Those goddman dogs', 'Raphael Bader', '48.192528', '16.283246', '/images/1.jpg', '23.12.2014');