import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="text-center bg-gray-300 mt-9 text-red-600">
          Hello there.
        </p>
      </main>
    </div>
  );
}
